language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
env:
  - WEBPACK_VERSION=1 HTML_WEBPACK_VERSION=2
  - WEBPACK_VERSION=4 HTML_WEBPACK_VERSION=3
install:
  - npm install --ignore-scripts
  - npm rm webpack
  - npm rm html-webpack-plugin
  - npm install webpack@WEBPACK_VERSION html-webpack-plugin@HTML_WEBPACK_VERSION --ignore-scripts || true
script:
  - npm test